# Generated by Django 4.0.4 on 2022-06-22 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_hombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hombre',
        ),
    ]
